import React, { useState } from 'react';
import ReactDOM from 'react-dom';
import { Outlet, useNavigate, useLocation } from 'react-router-dom';
import { jsPDF } from "jspdf";
import AdminSidebar from './AdminSidebar';
import { ToastProvider, useToast } from './Toast';
import '@/features/admin/styles/AdminDash.css';

// Portal Component for Modals
const ModalPortal = ({ children }) => {
    return ReactDOM.createPortal(children, document.body);
};

const AdminLayout = () => {
    const { showToast } = useToast();
    const navigate = useNavigate();
    const location = useLocation();
    const [sidebarActive, setSidebarActive] = useState(false);
    const [isNotificationsModalOpen, setIsNotificationsModalOpen] = useState(false);

    // State for expanded notification
    const [expandedNotification, setExpandedNotification] = useState(null);

    // Mock Notifications Data (moved from AdminHome)
    const [notifications, setNotifications] = useState([
        { id: 1, title: 'New Message from Rohan Silva (INST001)', message: 'INST001 - Rohan Silva sent a message: "Monthly report submission delay due to heavy rains."', details: 'Full message: "Dear Admin, I am writing to inform you that the monthly report for Padaviya area will be delayed by 2 days due to heavy rains disrupting field visits. I apologize for the inconvenience."', time: '10 mins ago', unread: true },
        { id: 2, title: 'New Message from Sunil Perera (FARM001)', message: 'FARM001 - Sunil Perera sent a message with Attachment: "Pest_Image_001.jpg"', details: 'Attachment: Pest_Image_001.jpg (2.5MB). Message: "Found this pest in my paddy field today. Please identify and suggest a remedy."', time: '1 hour ago', unread: true },
        { id: 3, title: 'New Message from Kamala Fernando (FARM002)', message: 'FARM002 - Kamala Fernando sent a message: "Inquiry about next season\'s seed distribution."', details: 'Full message: "Hello, when will the seed distribution for the Yala season begin? We need to prepare the land accordingly."', time: '5 hours ago', unread: false },
        { id: 4, title: 'New Message from Anura (INST003)', message: 'INST003 - Anura Wickramasinghe sent a message: "Requesting additional fertilizer allocation for Vahalkada."', details: 'Full message: "The current fertilizer stock is insufficient for the expanded cultivation area in Vahalkada. Requesting an additional 500kg of Urea."', time: '1 day ago', unread: false }
    ]);

    const openNotificationsModal = () => {
        setIsNotificationsModalOpen(true);
    };

    const closeNotificationsModal = () => {
        setIsNotificationsModalOpen(false);
        setExpandedNotification(null);
    };

    const toggleNotificationExpand = (id) => {
        setExpandedNotification(expandedNotification === id ? null : id);
        // Mark as read if opening
        if (expandedNotification !== id) {
            setNotifications(notifications.map(n => n.id === id ? { ...n, unread: false } : n));
        }
    };

    const deleteNotification = (id) => {
        setNotifications(notifications.filter(n => n.id !== id));
        if (expandedNotification === id) {
            setExpandedNotification(null);
        }
    };

    const downloadNotificationPDF = (e, notification) => {
        e.stopPropagation();
        const doc = new jsPDF();

        // Title
        doc.setFontSize(16);
        doc.setTextColor(93, 64, 55); // --primary color
        doc.text("Notification Details", 20, 20);

        // Info
        doc.setFontSize(12);
        doc.setTextColor(0, 0, 0);
        doc.text(`Title: ${notification.title}`, 20, 40);
        doc.text(`Time: ${notification.time}`, 20, 50);

        // Message
        doc.setFontSize(14);
        doc.text("Message Content:", 20, 70);
        doc.setFontSize(12);
        doc.setTextColor(50, 50, 50);

        // Split text to fit page
        const splitTitle = doc.splitTextToSize(notification.message, 170);
        doc.text(splitTitle, 20, 80);

        let yPos = 80 + (splitTitle.length * 7);

        if (notification.details) {
            yPos += 10;
            doc.setFontSize(14);
            doc.setTextColor(0, 0, 0);
            doc.text("Full Details:", 20, yPos);
            yPos += 10;
            doc.setFontSize(12);
            doc.setTextColor(50, 50, 50);
            const splitDetails = doc.splitTextToSize(notification.details, 170);
            doc.text(splitDetails, 20, yPos);
        }

        // Footer
        doc.setFontSize(10);
        doc.setTextColor(150, 150, 150);
        doc.text("Generated by AgriConnect Admin Dashboard", 20, 280);

        // Save
        doc.save(`notification_${notification.id}.pdf`);
        showToast('Notification details downloaded as PDF', 'success');
    };

    const getCurrentPage = () => {
        const path = location.pathname.split('/admin/')[1];
        return path || 'home';
    };

    const activePage = getCurrentPage();

    const handleNavigation = (path) => {
        navigate(path);
        if (window.innerWidth <= 768) {
            setSidebarActive(false);
        }
    };

    const logout = () => {
        navigate('/login');
    };

    return (
        <div className="admin-dashboard">
            <AdminSidebar
                activePage={activePage}
                sidebarActive={sidebarActive}
                handleNavigation={handleNavigation}
                logout={logout}
                location={location}
            />

            <div className={`admin-main-content ${sidebarActive ? 'active' : ''}`}>
                <div className="admin-header">
                    <div className="header-left">
                        <h2>Admin Dashboard</h2>
                    </div>
                    <div className="user-info">
                        <div className="notification-container">
                            <button className="notification-btn" onClick={openNotificationsModal}>
                                <i className="fas fa-bell"></i>
                                {notifications.filter(n => n.unread).length > 0 && (
                                    <div className="notification-badge">{notifications.filter(n => n.unread).length}</div>
                                )}
                            </button>
                        </div>
                        <div className="user-avatar clickable" onClick={() => navigate('/admin/settings')}>AD</div>
                        <div onClick={() => navigate('/admin/settings')} className="clickable">Admin User</div>
                    </div>
                </div>

                <div className="admin-content">
                <ToastProvider>
                    <Outlet context={{ openNotificationsModal }} />
                </ToastProvider>
            </div>
            </div>

            {/* Notifications Modal */}
            {isNotificationsModalOpen && (
                <ModalPortal>
                    <div className="admin-modal active" id="notificationsModal">
                        <div className="admin-modal-content large">
                            <div className="admin-modal-header">
                                <div className="admin-modal-title">Notifications</div>
                                <button className="admin-modal-close-round" onClick={closeNotificationsModal}>
                                    <i className="fas fa-times"></i>
                                </button>
                            </div>
                            <div className="admin-modal-body">
                                <div className="notification-list">
                                    {notifications.length > 0 ? (
                                        notifications.map((notification) => (
                                            <div
                                                key={notification.id}
                                                className={`notification-item ${notification.unread ? 'unread' : ''} notification-item-content-wrapper`}
                                                onClick={() => toggleNotificationExpand(notification.id)}
                                            >
                                                <div className="notification-header-row">
                                                    <div className="notification-content notification-main-content">
                                                        <div className="notification-title notification-title-row">
                                                            {notification.title}
                                                            <i
                                                                className={`fas fa-chevron-${expandedNotification === notification.id ? 'up' : 'down'} notification-expand-icon`}
                                                            ></i>
                                                        </div>
                                                        <div className="notification-message">{notification.message}</div>
                                                        <div className="notification-time">
                                                            <i className="far fa-clock"></i> {notification.time}
                                                        </div>
                                                    </div>
                                                    <button
                                                        className="notification-delete-btn"
                                                        onClick={(e) => {
                                                            e.stopPropagation();
                                                            deleteNotification(notification.id);
                                                        }}
                                                        title="Delete Notification"
                                                    >
                                                        <i className="fas fa-trash-alt"></i>
                                                    </button>
                                                </div>
                                                {expandedNotification === notification.id && (
                                                    <div className="notification-details-expanded">
                                                        <div className="notification-details-text">{notification.details}</div>
                                                        <button
                                                            className="btn btn-sm btn-outline btn-pdf-download"
                                                            onClick={(e) => downloadNotificationPDF(e, notification)}
                                                        >
                                                            <i className="fas fa-file-pdf"></i> Download as PDF
                                                        </button>
                                                    </div>
                                                )}
                                            </div>
                                        ))
                                    ) : (
                                        <div className="no-notifications-container">
                                            <i className="far fa-bell-slash no-notifications-icon"></i>
                                            No notifications
                                        </div>
                                    )}
                                </div>
                                <div className="admin-modal-footer">
                                    <button className="btn btn-secondary" onClick={closeNotificationsModal}>Close</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </ModalPortal>
            )}
        </div>
    );
};

export default AdminLayout;
