-- Migration: Create meetings table
CREATE TABLE IF NOT EXISTS `meetings` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `meetingTitle` VARCHAR(255) NOT NULL,
    `meetingDate` DATE NOT NULL,
    `meetingTime` VARCHAR(20) NOT NULL,
    `meetingDuration` VARCHAR(20) DEFAULT '30',
    `meetingNotes` TEXT NULL,
    `instructorNote` TEXT NULL,
    `status` ENUM('pending','accepted','rejected','declined','reschedule','cancelled') DEFAULT 'pending',
    `requestedBy` ENUM('farmer','instructor') NOT NULL,
    `farmer_id` INT NOT NULL,
    `instructor_id` INT NULL,
    `division` VARCHAR(100) NULL,
    `suggestedDate` DATE NULL,
    `suggestedTime` VARCHAR(20) NULL,
    `zoomLink` VARCHAR(255) NULL,
    `cancelReason` TEXT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`farmer_id`) REFERENCES `users`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`instructor_id`) REFERENCES `users`(`id`) ON DELETE SET NULL,
    INDEX `idx_meetings_farmer` (`farmer_id`),
    INDEX `idx_meetings_instructor` (`instructor_id`),
    INDEX `idx_meetings_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
